apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: democ
      image: alpine
      command: ["sleep", "3600"]
      env:
        # Define the environment variable
        - name: USER_NAME # Notice that the case is different here
          valueFrom:
            configMapKeyRef:
              name: app-configmap           # The ConfigMap this value comes from.
              key: name # The key to fetch.
        - name: USER_ID
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: id
        - name: USER_GENDER
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: gender