apiVersion: v1
kind: Pod
metadata:
  name: init-container-demo
  labels:
    app: demo
    tier: 2-tier
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "techo test1 && sleep 20"]
  - name: init-mydb
    image: busybox:1.28
    command: ['sh', '-c', "echo test2 && sleep 10"]
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 300']