apiVersion: v1
kind: Pod
metadata:
  name: nginx-tomcat
spec:
  containers:
  - name: nginx-example
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: pap-tomcat
    image: seetha123/pac_tomcat:latest