apiVersion: v1
kind: Pod
metadata:
  name: apache
  labels:
    app: apache
spec:
  containers:
  - name: apache
    image: seetha123/k8s-demo-apache # image name
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80