apiVersion: v1
kind: Service
metadata:
  name: apache-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
    name: apache-http
  selector:
    app: apache
