apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: secured
    - name: MYSQL_DATABASE
      value: example_db
    - name: MYSQL_USER
      value: example_db_user
    - name: MYSQL_PASSWORD
      value: example_db_pass
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: initdb
        mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: initdb
      configMap:
        name: initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: initdb-config
data:
  initdb.sql: |
      use example_db;
      DROP TABLE IF EXISTS `example_table`;
      CREATE TABLE `example_table` (
        `id`        bigint(20)   NOT NULL,
        `NAME`      varchar(255) NOT NULL,
        PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

      LOCK TABLES `example_table` WRITE;
      /*!40000 ALTER TABLE `example_table` DISABLE KEYS */;
      INSERT INTO `example_table` (id, NAME)
      VALUES
      ( 1, 'abc'), 
      ( 2, 'xyz'), 
      ( 3, 'pqr'),
      ( 4, 'efg');
      UNLOCK TABLES;