apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: seetha123/k8s-demo-tomcat
    imagePullPolicy: IfNotPresent
    env:
    - name: JDBC_URL
      value: jdbc:mysql://mysql-svc:3306/example_db
    - name: TABLE_NAME
      value: example_table
    - name: JDBC_USER
      value: example_db_user
    - name: JDBC_PASS
      value: example_db_pass
    ports:
    - containerPort: 8080